//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NewCSBot.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_CONNECT_GAME                101
#define IDD_CUSTOMBAN                   102
#define ID_SCHED_DELETE                 103
#define IDD_CONNECTIRC                  104
#define IDC_PLAYER_BAN_2HRS             104
#define ID_SCHED_EDIT                   105
#define IDC_PLAYER_BAN_5HRS             105
#define IDD_OPTIONS_DLG                 106
#define ID_ENTER                        106
#define ID_SCHED_RUNNOW                 106
#define IDP_SOCKETS_INIT_FAILED         107
#define IDR_MAINFRAME                   128
#define IDR_NEWCSBTYPE                  129
#define IDD_PROFILENAME                 135
#define IDD_WONIDDLG                    136
#define IDD_OPTIONS_GENERAL             138
#define IDD_OPTIONS_IRC_IN              140
#define IDD_OPTIONS_IRC_OUT             141
#define IDD_OPTIONS_IRC_MSGS            142
#define IDD_INSERT_ONCE                 143
#define IDD_INSERT_MINUTE               144
#define IDD_INSERT_HOUR                 145
#define IDD_INSERT_DAY                  146
#define IDD_EDIT_IRC_MESSAGE            148
#define IDD_IRC_COLOR                   149
#define IDD_EDIT_TRUSTED_PERSON         150
#define IDD_OPTIONS_SUMMON              151
#define IDD_WINIDDBDLG                  152
#define IDD_CONNECT_GAME_GENERAL        153
#define IDD_CONNECT_CMDS                154
#define IDD_CONNECT_IRC_GENERAL         155
#define IDD_OPTIONS_IRC_GENERAL         156
#define IDD_OPTIONS_IRC_MSGS_MSGS       157
#define IDD_UPDATENOTIFY                158
#define IDD_OPTIONS_IRC_MSGS_COLORS     159
#define IDB_IMAGELIST                   159
#define IDD_OPTIONS_PLAYERLIST          160
#define IDD_EDIT_PLAYERLIST_COMMAND     161
#define IDB_TOOLBAR2                    162
#define IDD_SUMMON_COMMAND              163
#define IDD_CONNECT_GAME_RECONNECT      164
#define IDD_CONNECT_RECONNECT           164
#define IDD_CONNECT_IRC_IDENT           165
#define IDB_TOOLBARDISABLED             167
#define IDR_TRAY                        169
#define IDR_TRAY16                      169
#define IDC_TOPICTEXT                   1000
#define IDC_SERVERNAME                  1001
#define IDC_PORT                        1002
#define IDC_LOCALIP                     1003
#define IDC_LINE                        1004
#define IDC_GUESS                       1005
#define IDC_ADDLINE                     1006
#define IDC_LOCALLOGPORT                1007
#define IDC_REMOVELINE                  1008
#define IDC_LOCALRCONPORT               1009
#define IDC_LIENLIST                    1010
#define IDC_RCON                        1011
#define IDC_AMOUNT                      1012
#define IDC_TYPE                        1013
#define IDC_CHANNELNAME                 1014
#define IDC_NICKNAME                    1015
#define IDC_USERID                      1016
#define IDC_ADDPROFILE                  1017
#define IDC_CHANNELPASSWORD             1017
#define IDC_FULLNAME                    1018
#define IDC_REMOVEPROFILE               1019
#define IDC_PASSWORD                    1020
#define IDC_RENAMEPROFILE               1021
#define IDC_NAME                        1022
#define IDC_IRCRCON                     1023
#define IDC_PROFILES                    1024
#define IDC_IRCINFO                     1024
#define IDC_CHANGE_TOPIC                1025
#define IDC_IRCPLAYER                   1025
#define IDC_ADDIRCPROFILE               1026
#define IDC_IRCTEAMS                    1026
#define IDC_RCONTIMEOUT                 1027
#define IDC_REMOVEIRCPROFILE            1028
#define IDC_CASE                        1028
#define IDC_LOG_CONNECT                 1029
#define IDC_RENAMEIRCPROFILE            1030
#define IDC_LOG_JOIN                    1031
#define IDC_LOG_SAY                     1033
#define IDC_LOG_SAYTEAM                 1035
#define IDC_IRCRCONLOGIN                1036
#define IDC_REFRESH                     1037
#define IDC_LOG_KILL                    1038
#define IDC_TRUSTLIST                   1039
#define IDC_WONID                       1040
#define IDC_TRUSTADD                    1041
#define IDC_LOG_ROUNDEND                1042
#define IDC_TRUSTEDIT                   1043
#define IDC_EDITLINE                    1044
#define IDC_LOG_OBJECTIVES              1045
#define IDC_TRUSTDELETE                 1046
#define IDC_REMEMBER                    1047
#define IDC_ADDWONID                    1048
#define IDC_INTEGRATE                   1049
#define IDC_MESSAGE                     1049
#define IDC_LOG_OBJECTIVES2             1050
#define IDC_MEANING                     1050
#define IDC_MESSAGES                    1051
#define IDC_DEFAULT                     1051
#define IDC_ADDNAME                     1052
#define IDC_REVERT                      1052
#define IDC_LINELIST                    1053
#define IDC_FOREGROUND                  1053
#define IDC_LOG_SERVER                  1054
#define IDC_BACKGROUND                  1054
#define IDC_FIND                        1055
#define IDC_DELETELINE                  1056
#define IDC_LIST                        1057
#define IDC_SAMPLET                     1057
#define IDC_RUNLEVEL                    1060
#define IDC_SAMPLECT                    1061
#define IDC_LOG_WINS                    1063
#define IDC_SAMPLESPEC                  1064
#define IDC_SAMPLE                      1065
#define IDC_NEWEONID                    1067
#define IDC_LOGTOFILE                   1069
#define IDC_NICK                        1070
#define IDC_NEWNAME                     1072
#define IDC_PASS                        1073
#define IDC_LOGIRCTOFILE                1075
#define IDC_PER_LOGIN                   1076
#define IDC_FILENAME                    1077
#define IDC_PER_RCON                    1078
#define IDC_FINDNAME                    1079
#define IDC_AUTOLOGOFF                  1080
#define IDC_LOGBROWSE                   1081
#define IDC_LOGOFF_MINUTES              1082
#define IDR_RAWLOG                      1083
#define IDC_IRCCHAT                     1084
#define IDC_IRCFOLDER                   1085
#define IDC_IRCPM                       1086
#define IDC_COUNT                       1087
#define IDC_WONIDDB                     1088
#define IDC_ALLOWSUMMON                 1089
#define IDC_IRCCM                       1090
#define IDR_PLAYERLIST                  1091
#define IDC_SUMMONWORD                  1092
#define IDC_IRCBROWSE                   1093
#define IDC_SUMMON_FLASH                1094
#define IDC_WONIDFOLDER                 1095
#define IDC_SUMMON_PLAY                 1096
#define IDR_RCON                        1097
#define IDC_SUMMON_PLAYFILE             1098
#define IDC_WONIDBROWSE                 1099
#define IDC_ALLOWSUMMONTEAM             1100
#define IDR_IRC                         1101
#define IDC_CONNECTCMDS                 1102
#define IDC_DELETENAME                  1103
#define IDC_DISCONNECTCMDS              1104
#define IDR_SCHED                       1105
#define IDC_EXPORT                      1106
#define IDR_TRAY256                     1106
#define IDC_ADDCMD                      1107
#define ID_TRAY_RESTORE                 1108
#define IDC_EDITCMD                     1109
#define IDC_IMPORT                      1110
#define IDC_DELETECMD                   1111
#define IDC_ADDDCMD                     1112
#define IDC_ADDCMD2                     1113
#define IDC_EDITDCMD                    1114
#define IDC_FINDWONID                   1115
#define IDC_EDITCMD2                    1116
#define IDC_DELETEDCMD                  1117
#define IDC_SELECTWONID                 1118
#define IDC_DELETECMD2                  1119
#define IDC_FINDNICKNAME                1120
#define IDC_VIEWNICKNAMES               1121
#define IDC_VIEWWONID                   1122
#define IDC_GUESSHARDER                 1123
#define IDC_LINES                       1124
#define IDC_SECONDS                     1125
#define IDC_REDIRECTBACK                1126
#define IDC_LINK                        1127
#define IDC_GAMETYPE                    1128
#define IDC_FILTER                      1129
#define IDC_TABS                        1130
#define IDC_STATIC1                     1131
#define IDC_STATIC2                     1132
#define IDC_STATIC3                     1133
#define IDC_STATIC4                     1134
#define IDC_STATIC5                     1135
#define IDC_STATIC6                     1136
#define IDC_STATIC7                     1137
#define IDC_RECONNECTTOIRC              1138
#define IDC_STATIC9                     1138
#define IDC_RCONNECTSEC                 1139
#define IDC_RECONNECTTIMES              1140
#define IDC_CMDS                        1141
#define IDC_CMDS2                       1142
#define IDC_STATIC8                     1143
#define IDC_LABEL                       1144
#define IDC_GAMENAME                    1145
#define IDC_TREE                        1146
#define IDC_NOTIFYUPDATES               1147
#define IDC_MSG                         1148
#define IDC_ENABLE                      1149
#define IDC_SCOPE                       1150
#define IDC_COMMANDS                    1158
#define IDC_MOVEUP                      1162
#define IDC_MOVEDOWN                    1163
#define IDC_COMMAND                     1164
#define IDC_WEBSITE                     1165
#define IDC_RECONNECT                   1166
#define IDC_EDIT1                       1167
#define IDC_NOACTIVITY                  1167
#define IDC_RECONNECTSEC                1167
#define IDC_IRCDELAY                    1167
#define IDC_IRCCM_PREFIX                1167
#define IDC_GAMECONNECTTIMEOUT          1167
#define IDC_ALLOWCOMMANDS               1168
#define IDC_ALLOWEDCOMMANDS             1169
#define IDC_UA                          1170
#define IDC_MORETAGS                    1171
#define IDC_REVERTDEFAULT               1172
#define IDC_IDENT                       1173
#define IDC_CLOSEIDENTAFTERQUERY        1174
#define IDC_RECONNECTLABEL1             1176
#define IDC_RECONNECTLABEL2             1177
#define IDC_RECONNECTLABEL3             1178
#define IDC_INACTIVITY                  1179
#define IDC_INACTIVITYTIMEOUT           1180
#define IDC_INACTIVITYLABEL             1181
#define IDC_WARNLOGOFF                  1182
#define IDC_LOGQUERYTYPE                1184
#define IDC_FILTER_LOG                  1189
#define IDC_PLAYER_KICK                 2000
#define IDC_PLAYER_BAN_5MIN             2001
#define IDC_PLAYER_BAN_30MIN            2002
#define IDC_PLAYER_BAN_3DAY             2003
#define IDC_PLAYER_BAN_FOREVER          2004
#define IDC_PLAYER_BAN_CUSTOM           2005
#define IDC_PLAYER_INFO                 2006
#define IDC_FORCE_REFRESH               2007
#define IDC_COMMENT                     2100
#define IDC_ADD                         2101
#define IDC_EDIT                        2102
#define IDC_DELETE                      2103
#define IDC_DATE                        2104
#define IDC_TIME                        2105
#define IDC_CRITICAL                    2106
#define IDC_AMOUNTSPIN                  2107
#define IDC_ONTHEHOUR                   2108
#define IDC_TEAM0                       3000
#define IDC_TEAM1                       3001
#define IDC_TEAM2                       3002
#define IDC_TEAM3                       3003
#define IDC_TEAM4                       3004
#define IDC_TEAM5                       3005
#define IDC_SAMPLE0                     3100
#define IDC_SAMPLE1                     3101
#define IDC_SAMPLE2                     3102
#define IDC_SAMPLE3                     3103
#define IDC_SAMPLE4                     3104
#define IDC_SAMPLE5                     3105
#define IDC_COLOR0                      3200
#define IDC_COLOR1                      3201
#define IDC_COLOR2                      3202
#define IDC_COLOR3                      3203
#define IDC_COLOR4                      3204
#define IDC_COLOR5                      3205
#define ID_VIEW_RAWLOG                  32771
#define ID_VIEW_PLAYERS                 32772
#define ID_VIEW_RCON                    32773
#define ID_VIEW_IRC                     32774
#define ID_VIEW_OPTIONS                 32775
#define ID_SERVER_CONNECT_IRC           32777
#define ID_SERVER_WONIDS                32783
#define ID_VIEW_SCHED                   32792
#define ID_INSERT_ONCE                  32794
#define ID_INSERT_MINUTE                32795
#define ID_INSERT_HOUR                  32796
#define ID_INSERT_DAY                   32797
#define ID_INSERT_WEEK                  32798
#define ID_INSERT_MONTH                 32799
#define ID_HELP_SITE                    32801
#define ID_HELP_REPORT                  32802
#define ID_HELP_FORUMS                  32803
#define ID_MUTE                         32805
#define ID_SERVER_CONNECT_GAME          32807
#define ID_HELP_UPDATE                  32808
#define ID_HELP_UNITEDADMINS            32809

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1190
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
